### ISSUE TITLE
Escape key breaks plugin accessibility

### ISSUE THREAD

**Issue by yuvals1** [mikavilpas/yazi.nvim#423]
Pressing Escape while in the plugin:

Makes the plugin inaccessible
Requires quitting via Neovim command line

**Comment by mikavilpas** [comment]
Hmm that's strange - for me the escape key causes no issues.

Could you follow https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md and see if you can reproduce the issue?

**Comment by mikavilpas** [comment]
That's strange. Glad you were able to narrow it down.

It reminds me of this https://github.com/mikavilpas/yazi.nvim/issues/295

**Comment by yuvals1** [comment]
any idea why would toggleterm affect yazi.nvim (and other nvim tui plugins) so bad?

**Comment by mikavilpas** [comment]
Hmm I'm not sure what the lagginess was like for you. But in the issue that I linked, using `<esc><esc>` as the mapping made pressing only one `<esc>` key wait for some time to see if the user wants to press a second `<esc>` or just one. This introduced some lag.

It seems that mapping is some kickstart default - I don't think it's a good idea because it might interfere with tui applications that use the escape key. If you want to disable it for yazi.nvim only, you can maybe use something like this:

```lua
    ---@type YaziConfig
    opts = {
      ---@diagnostic disable-next-line: missing-fields
      hooks = {
        ---@diagnostic disable-next-line: unused-local
        yazi_opened = function(_preselected_path, buffer, _config)
          vim.keymap.del("t", "<esc><esc>", { buffer = buffer })
        end,
      },
    }
```

I have not tested this, but I think it might work.
