### ISSUE TITLE
Rescaling the window break Yazi

### ISSUE THREAD

**Issue by Zeioth** [mikavilpas/yazi.nvim#53]
If after opening yazi
![screenshot_2024-04-25_21-24-46_212366744](https://github.com/mikavilpas/yazi.nvim/assets/3357792/83c3a21b-7ab0-4971-9130-33bf259c8d7b)

**Comment by Zeioth** [comment]
We resize the window, it won't re-scale to the new size.
![screenshot_2024-04-25_21-30-50_384044750](https://github.com/mikavilpas/yazi.nvim/assets/3357792/8d9a211d-4fb2-476b-ab96-9f20ef13de75)

Closing the Yazi window after this has happened, will display the message "Process exited 0".
![screenshot_2024-04-25_21-28-03_066734704](https://github.com/mikavilpas/yazi.nvim/assets/3357792/ec77a274-a944-433f-88c7-b55739fab74c)

**Comment by Zeioth** [comment]
Sorry I just noticed #39, closing.

**Comment by Zeioth** [comment]
Even though this might actually be a nvim bug (I also experience it by running yazi on :terminal), it's worth checking the ranger plugin https://github.com/kevinhwang91/rnvimr

They managed to overcome this limitation.

**Comment by mikavilpas** [comment]
Might be improved a bit with #59, but it will probably be useful to see how the rnvimr is able to avoid this issue altogether.

**Comment by mikavilpas** [comment]
I think I figured out how rnvimr does it, it seemed to use RPC (remote procedure calls) from nvim to ranger in order to work around the resizing by telling the file manager itself to resize.

The same thing could theoretically be done here if some kind of api for this became available in yazi.

Related https://github.com/sxyazi/yazi/issues/989

This can now be tracked in #39
