### ISSUE TITLE
Goto specific path relative to current working directory.

### ISSUE THREAD

**Issue by sohanemon** [mikavilpas/yazi.nvim#542]
In Yazi, pressing `gh` takes me to the home directory. However, I want it to take me to the current working directory when I’m working in a Neovim project.

Additionally, with `oil.nvim`, I have been using the following shortcuts to navigate to specific directories:

```lua
["gc"] = { function() goto({ "/components" }) end, desc = "Navigates to the /components directory" },
["gu"] = { function() goto({ "/components/ui", "/components" }) end, desc = "Navigates to /components/ui or /components directories" },
```

The `goto` function is defined as follows:

```lua
local function goto(paths)
  local cwd_base = vim.fn.getcwd()

  for _, path in ipairs(paths) do
    local cwd = cwd_base .. path
    if dir_exists(cwd) then
      local oil = require('oil')
      oil.close()
      oil.open_float(cwd)
      return
    end
  end

  print("No valid path found.")
end
```

Can I achieve similar functionality with Yazi?

**Comment by mikavilpas** [comment]
A good solution for this does not exist yet. Technically it's possible using this function, which sends a DDS (https://yazi-rs.github.io/docs/dds/) event telling yazi to switch to a new directory  https://github.com/mikavilpas/yazi.nvim/blob/6616bd5a24280d5a21d9110025451a69ebc9708e/lua/yazi/process/yazi_process_api.lua?plain=1#L16-L23

However, mapping keys in yazi.nvim is problematic right now. If you add a yazi.nvim level mapping to `gh`, it will intercept those keys from yazi in all cases (including when doing other operations such as renaming files). For this reason the keymappings are almost always control+something so that they have a smaller chance of conflicting with yazi keymappings.

A better solution to this would be to add the keymapping in yazi itself. I could publish that as an environment variable so the embedded yazi can access it. Then you would need to add a yazi keymapping to change yazi's directory to the dir in that environment variable.

However, that will only work when you are running yazi inside of neovim - if you run it outside of neovim, the environment variable will not be available.

I think the ideal solution to all of this would be creating a yazi plugin for project navigation - it could for example identify the project root based on where the .git directory is, or something fancier if needed.

What do you think?

**Comment by sxyazi** [comment]
@sohanemon You may want this tip https://yazi-rs.github.io/docs/tips#cd-to-git-root

**Comment by sohanemon** [comment]
Thank you for your suggestion! I found a workaround for the issue. Let me know if you have any suggestions for improvement.

```lua
local function path_exists(path)
	local handle = io.popen('[ -e "' .. path .. '" ] && echo exists')
	if handle == nil then
		return false
	end
	local result = handle:read("*a")
	handle:close()
	return result:find("exists") ~= nil
end

return {
	entry = function(self, args)
		for _, path in ipairs(args) do
			local is_exist = path_exists("$CWD" .. path)
			if is_exist then
				ya.manager_emit("cd", { "$CWD" .. path })
				return
			end
		end

		local content = (args and args[1] or "Unknown path") .. " not found"
		ya.notify({
			title = "No valid path",
			content = content,
			timeout = 3,
		})
	end,
}
```

**Comment by sohanemon** [comment]
> @sohanemon You may want this tip https://yazi-rs.github.io/docs/tips#cd-to-git-root

I am using this way right now `alias vi='export CWD="$(pwd)"; nvim'`
Thank you for your suggestion, I will have a look in it.
