### ISSUE TITLE
config options chosen_file_path and events_file_path required on Windows

### ISSUE THREAD

**Issue by lzybkr** [mikavilpas/yazi.nvim#546]
If you don't specify the configuration options `chosen_file_path` and `events_file_path`, yazi will fail to launch successfully because Windows doesn't normally have a `/tmp` directory, so Yazi can't find `/tmp/yazi_filechosen`. or redirect to `/tmp/yazi.nvim.events`.

After adding the following to my config:

```lua
            opts = {
                chosen_file_path = vim.fn.tempname(),
                events_file_path = vim.fn.tempname(),
            },
```

The extension seems to work correctly.

**Comment by mikavilpas** [comment]
Hi! I think you might be running an old version of yazi.nvim. Is it possible for you to update to the most recent version?

Using `/tmp/` as the default directory was removed back in May in this commit https://github.com/mikavilpas/yazi.nvim/commit/95eb780cab5f8535a217a9d9dc611f17226eab8d

Now `vim.fn.tempname()` is used as the default. Also note that `events_file_path` no longer exists because `ya` (the yazi command line utility that's bundled with yazi) is used to read events now.

**Comment by lzybkr** [comment]
Lazy was telling me I had the latest, but that was for the `master` branch. I switched to `main` and that seems to have been it.
