### ISSUE TITLE
Closing Yazi while renaming causes the "Invalid buffer id" error

### ISSUE THREAD

**Issue by sxyazi** [mikavilpas/yazi.nvim#594]
I occasionally get this error: 

```lua
Error executing vim.schedule lua callback: .../ika/.local/share/nvim/lazy/yazi.nvim/lua/yazi/utils.lua:356: Invalid buffer id: 1163
stack traceback:
	[C]: in function 'nvim_buf_call'
	.../ika/.local/share/nvim/lazy/yazi.nvim/lua/yazi/utils.lua:356: in function <.../ika/.local/share/nvim/lazy/yazi.nvim/lua/yazi/utils.lua:355>
	[C]: in function 'wait'
	...eovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/client.lua:758: in function <...eovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/client.lua:747>
	[C]: in function 'pcall'
	...-lsp-file-operations/lsp-file-operations/will-rename.lua:21: in function 'getWorkspaceEdit'
	...-lsp-file-operations/lsp-file-operations/will-rename.lua:49: in function 'callback'
	....local/share/nvim/lazy/yazi.nvim/lua/yazi/lsp/rename.lua:15: in function 'file_renamed'
	...azi.nvim/lua/yazi/event_handling/yazi_event_handling.lua:76: in function 'process_events_emitted_from_yazi'
	/Users/ika/.local/share/nvim/lazy/yazi.nvim/lua/yazi.lua:72: in function 'on_exit'
	...re/nvim/lazy/yazi.nvim/lua/yazi/process/yazi_process.lua:55: in function <...re/nvim/lazy/yazi.nvim/lua/yazi/process/yazi_process.lua:41>
```

It's not always reproducible and only happens when I quickly close Yazi and go back to nvim after triggering a rename. 

Since I use noice.nvim, it appears in the top right corner of the UI, blocking part of the content, which is a bit annoying. 

I think a simple fix would be to check if the buffer ID is still valid using [`nvim_buf_is_valid`](https://neovim.io/doc/user/api.html#nvim_buf_is_valid()) before [calling `vim.api.nvim_buf_call`](https://github.com/mikavilpas/yazi.nvim/blob/a54ec0506fc40afa8f0215931bcf462347d77331/lua/yazi/utils.lua#L356C5-L356C26), just in case. It's more like a safety check and wouldn't break anything existing.

**Comment by mikavilpas** [comment]
Nice catch, I don't think I have seen this myself. I'll add that check and let's see if it can be avoided 👍🏻

**Comment by mikavilpas** [comment]
By the way, I think it's possible to configure noice.nvim to have the popups displayed at the bottom right instead of the top right. I had this setting before https://github.com/folke/snacks.nvim was added to lazyvim (which I use). That changed the way it should be done.

It looks like without snacks.nvim I did it like [this](https://github.com/mikavilpas/dotfiles/commit/4bd159d49b1b70e3224cfdbc8a33d5782bbd0e57), and right now (with snacks.nvim) I do it [like this](https://github.com/mikavilpas/dotfiles/blob/0a406458250b93c6fef2993da2bae6f09bd3838f/.config/nvim/lua/plugins/ui.lua?plain=1#L20-L23)

If you like the idea, it might reduce the amount of annoying messages that cover your work 🙂

**Comment by sxyazi** [comment]
Cool, definitely check it out, and thanks for the fix!
